---
title: "Presidential Election Maps for United Sates from 1920s"
author: "Team FiveThirtyNine"
date: "12/3/2017"
output: html_document
---
# Libraries Needed
```{r, message=F}
library(stringr)
library(dplyr)
library(tidyr)
library(shiny)
library(rvest)
library(ggplot2)
library(maps)
library(leaflet)
library(sf)
library(datamap)
devtools::install_github("hrbrmstr/albersusa")
library(albersusa)
```

# Scraping Data from Wikipedia
```{r}
get_election_data=function(year){

  html_str<-paste0("https://en.wikipedia.org/wiki/United_States_presidential_election,_",year,"#Results_by_state")
 
  
  wiki<-read_html(html_str)
  wikitables<-wiki%>%html_nodes(".wikitable.sortable")
  
  for(i in 1:length(wikitables)){
    temp=wikitables[[i]]%>%html_table(fill=TRUE)
    if(nrow(temp)>49)
      {
        result_table=temp
        break
      }
  }
  
  #set uniform column names
  if(year == 1992){
    colnames(result_table)<-paste(result_table[1,],result_table[2,]) %>%
      str_replace_all("\n"," ") %>%
      str_replace_all("^\\s","")
    result_table<-result_table[-c(1,2),]
  }
  else{
    colnames(result_table)<-paste(colnames(result_table),result_table[1,]) %>%
      str_replace_all("\n"," ") %>%
      str_replace_all("^\\s","")
    result_table<-result_table[-1,]
  }
  
  d = result_table
  
  colnames(d) = colnames(d) %>%
    str_replace_all("\\s$","") %>%
    str_replace_all("^E$","electoral votes") %>%
    str_replace_all("(?<!^)[Ee]lectoral votes","E") %>%
    str_replace_all("Top.+/R\\)","Margin") %>%
    str_replace_all("#","Vote") %>%
    str_replace("State Total Vote","Total Vote") %>%
    str_replace("State [Tt]otal$|Total State$|^Total$","State Abbr") %>%
    str_replace("State or district","State") %>%
    str_replace_all("\\★","")
  
  #remove superfluous columns
  omit <- c("Electoral method","Total Status")
  d = d[,which(!(colnames(d) %in% omit))]
  
  #formatting dataframe
  dd = apply(d,2,function(x){
    x %>% str_replace_all("–|−","-") %>% str_replace_all("N/A","-") %>%
      str_replace_all("^-$|^$","0") %>% str_replace_all("%","") %>%
      str_replace_all(",","") %>% str_replace_all("\\†","") %>%
      str_replace_all("\\★","")
    }) %>% as.data.frame(stringsAsFactors = FALSE)
  
  #turn appropriate columns into numeric variables
  idx = which(str_detect(colnames(dd),"State"))
  
  dd[,-idx] = lapply(dd[,-idx],as.numeric)
  dd$`Margin Vote`<-abs(dd$`Margin Vote`)
  dd$`Margin %`<-abs(dd$`Margin %`)
  
  
  #add electoral votes column if doesn't already exist
  if(!("electoral votes" %in% colnames(dd))){
    dd = dd %>% mutate(
      elec_vote = rowSums(dd[,str_detect(colnames(dd),"E$")])
    )
    colnames(dd)[colnames(dd) == "elec_vote"] = "electoral votes"
  }
  
  #add winner column and alter state column
  dd = dd %>%
    mutate(Winner = apply(dd,1,function(x){names(
      which.max(x[str_detect(colnames(dd),"E$")])) %>% 
        str_replace("\\sE$","")}),
      State = `State Abbr` %>% str_extract_all("[:upper:]{2}") %>% unlist()
      ) %>% select(-`State Abbr`)
  
  #rename clean output
  clean_table = dd

  return(clean_table)
}

# year=2016

test<-get_election_data(1940)

a<-get_election_data(2016)
b<-get_election_data(1992)


```

# Draw US map
```{r}
# way 1
mapStates<-map("state",fill=TRUE,plot=FALSE)
leaflet(data=mapStates)%>%addTiles()%>%addPolygons(fillColor = topo.colors(10,alpha=NULL),stroke = FALSE)

# way 2
all_states <- map_data("state")
ggplot()+
  geom_polygon(data=all_states, aes(x=long, y=lat, group=group),colour="white")

#using albersusa
usa <- usa_sf() %>% mutate(State = as.character(iso_3166_2))
k <- b %>% select(State,`Winner`,`electoral votes`,`Margin %`) %>%
  mutate(`Winner` = ifelse(str_detect(.$`Winner`,"Republican"),1,               
                           ifelse(str_detect(.$`Winner`,"Democratic"),2,3))
         )
kk <- left_join(usa,k, by ="State")
kk[is.na(kk)] <- 0

pal <- colorNumeric(c("white","red","blue","green"),0:3)
map <- leaflet(kk) %>%
  addPolygons(smoothFactor = 0.2, fillOpacity = 0.8,
              fillColor = ~pal(Winner),color = "black", weight = 1, opacity = 1)

#using datamap
us_state_map <- Datamaps$new()
us_state_map$set(
  scope = 'usa',
  legend = TRUE,
  labels = TRUE
)

#test of pie chart
pi_r = b[nrow(b),which(str_detect(colnames(test),"Republican Vote"))][[1]]
pi_d = b[nrow(b),which(str_detect(colnames(test),"Democratic Vote"))][[1]]
pi_o = b[nrow(b),which(str_detect(colnames(test),"Total Vote"))][[1]] - sum(pi_r,pi_d)
x<-c(pi_r,pi_d,pi_o)

pie(x, labels = paste0(round(100*x/sum(x), 1),"%"), main = "Popular Vote",col=c("red","blue","grey"))
legend("topright",
       c(colnames(b) %>% str_extract("\\w+(?=\\sRepublican)") %>%
           na.omit() %>% unique(),
         colnames(b) %>% str_extract("\\w+(?=\\sDemocratic)") %>%
           na.omit() %>% unique(),"Others"),
       fill = c("red","blue","grey"))
```


# Shiny App
```{r}
#perhaps we could take cosmetic elements from Mine's SuperZip app: 
#https://shiny.rstudio.com/gallery/superzip-example.html

#map using albersusa
usa <- usa_sf() %>% mutate(State = as.character(iso_3166_2))
pal <- colorNumeric(c("white","red","indianred2",
                      "cornflowerblue","blue","green"),0:5)

shinyApp(
  ui = navbarPage("Electoral College",
    tabPanel("Electoral Map",
        div(class="outer"),
        leafletOutput("map", width="100%",height=600),
        absolutePanel(id = "elec_dat",top = 70,
                   left = 50,right = "auto", bottom = "auto",
                   width = 300, height = "auto", draggable = TRUE, fixed = TRUE,
          #wellPanel(
          h3("Presidential Election App"),
          numericInput("yearr","Year", min = 1920, max = 2016,
                       step = 4, value = 1996),
          actionButton("do", "See Results"),
          br(),br(),
          plotOutput("pop_vote"),
          dataTableOutput("elec_vote"),
          style = "opacity: 0.75"
          #)         
        )
    ),
    tabPanel("Election Data",
        sidebarLayout(
          sidebarPanel(
            selectInput("cand","Candidate",choices = NULL),
            selectInput("state","State", choices = NULL),
            actionButton("retrieve", "See Candidate Data")
          ),
        mainPanel(
          dataTableOutput("elec_dat")
        )
      )
    )
  ),
  server = function(input, output, session) 
  {
    
    #reactive values
    data <- eventReactive(input$do,{
      get_election_data(input$yearr)
    })
    
    k <- reactive({
      data() %>%
        mutate(`Party` = ifelse(
          str_detect(.$`Winner`,"Republican") & abs(.$`Margin %`)>10,1,
          ifelse(
            str_detect(.$`Winner`,"Republican") & abs(.$`Margin %`)<=10,2,
            ifelse(
              str_detect(.$`Winner`,"Democratic") & abs(.$`Margin %`)<=10,3,
              ifelse(
                str_detect(.$`Winner`,"Democratic") & abs(.$`Margin %`)>10,4,5
                ))))) %>%
        select(State,`Winner`,`electoral votes`,`Margin %`,`Party`)
    })
    
    kk <- reactive({
      left_join(usa,k(), by ="State") %>%
        mutate(`Party` = ifelse(is.na(.$`Party`),0,.$`Party`),
               `electoral votes` = ifelse(
                 is.na(.$`electoral votes`),0,.$`electoral votes`),
               `Margin %` = ifelse(is.na(.$`Margin %`),0,.$`Margin %`))
    })
    
    #render pie chart
    output$pop_vote <- renderPlot({
      pi_r = data()[nrow(data()),which(str_detect(
        colnames(data()),"Republican Vote"))][[1]]
      pi_d = data()[nrow(data()),which(str_detect(
        colnames(data()),"Democratic Vote"))][[1]]
      pi_o = data()[nrow(data()),which(str_detect(
        colnames(data()),"Total Vote"))][[1]] - sum(pi_r,pi_d)
      x = c(pi_r,pi_d,pi_o)
      
      r_lab = colnames(data()) %>% str_extract("\\w+(?=\\sRepublican)") %>%
                 na.omit() %>% unique()
      d_lab = colnames(data()) %>% str_extract("\\w+(?=\\sDemocratic)") %>%
                 na.omit() %>% unique()

      pie(x, labels = paste0(round(100*x/sum(x), 1),"%"),
          main = "Popular Vote",col=c("red","blue","grey"))
      legend("topleft",
             c(r_lab[1],d_lab[1],"Others"),
             fill = c("red","blue","grey"))
    })

    
    #render intial map
    output$map <- renderLeaflet({
      leaf = leaflet(usa) %>%
        addPolygons(smoothFactor = 0.2, fillOpacity = 0.8,
                    fillColor = "gray",color = "black",
                    weight = 1, opacity = 1)  %>% addLegend(position ="bottomright",
                  colors = c("red","indianred2","cornflowerblue","blue",
                          "green","white"),
                  labels = c("Strong Rep.","Weak Rep.","Weak Dem.","Strong Dem.",
                  "Other","No Info"),
                  title = "Party")
      })
    
    #update map
    
    observe({
      leafletProxy("map", data = kk()) %>%
        addPolygons(smoothFactor = 0.2, fillOpacity = 0.8,
                    fillColor = ~pal(Party),color = "black",
                    weight = 1, opacity = 1, layerId =~name)
        
    })
    
    observe({
       if(!is.null(input$map_shape_click)){
         print(input$map_shape_click)
       }
     })
    
    #update select choices
    list_cand<-eventReactive(input$do,{
      colnames(data()) %>%
        str_extract("^(?!Others|Total|Margin)[:upper:]\\w+(.*?)[:upper:]\\w+")%>%
        na.omit()%>%unique()
      #old regex
      #str_extract("[:upper:]\\w+[:space:][:upper:]\\w+")
      
    })
    observe({
      updateSelectInput(session, "cand","Candidate",
                      choices=c("none",list_cand()))
  })
    
    observe({
      updateSelectInput(session, "state","State",
                      choices=c("none",data()$State))
    })
    
    #function for popup content
    pop_content <- function(state,lat,lng){
      selectedState = kk() %>% filter(name == state)
      if(is.na(selectedState$`Winner`)){
        content = as.character(tagList(
          tags$h4(selectedState$name),
          sprintf("No Information Available")
        ))
      }else{
        content <-as.character(tagList(
          tags$h4(selectedState$name),
          sprintf("Electoral votes: %s", selectedState$`electoral votes`),tags$br(),
          sprintf("Winner: %s",selectedState$`Winner`),tags$br(),
          sprintf("Margin: %s%%",abs(selectedState$`Margin %`))
        ))
      }

      leafletProxy("map") %>% addPopups(lng, lat, content, layerId = state)
    }
    
    observe({
      leafletProxy("map") %>% clearPopups()
      event <- input$map_shape_click
      if(is.null(event)){
       return()
      }
      isolate({
        pop_content(event$id,event$lat,event$lng)
      })
    }) 

    cand_table<-eventReactive(input$retrieve,{
       if(input$cand!="none"&&input$state!="none"){
        a<-data()%>%select(starts_with(input$cand))
        aa<-cbind(data()$State,a)
        colnames(aa)<-c("State","Popular Vote","Percentage","Electoral Vote")
        aa%>%filter(State==input$state)
       }else if(input$state=="none"&&input$cand!="none"){
         a<-data()%>%select(starts_with(input$cand))
         aa<-cbind(data()$State,a)
         colnames(aa)<-c("State","Popular Vote","Percentage","Electoral Vote")
         aa
       }else if(input$state!="none"&&input$cand=="none"){
         a<-data()%>%filter(State==input$state)
         # aa<-as.data.frame(t(a))
        a
       }else{
         NULL
       }
      
    })
    output$elec_dat<-renderDataTable(
      cand_table())
      
  }
  
)
```